### PR TITLE
Monazite Chain Cleanup

### PR DESCRIPTION
**Pull request by jmoiron**
This fixes a number of issues with the Monazite chain.

- The Thorianite -> Alumina recipe yield was fixed; previously, you got less Thorium this route than with Magnesium.
- Alumina processing:
  - decomposes into `2xAl dust + 3KL O2`
  - EBF recipe from NH (`10x Alumina + 3x carbon -> 4x Aluminium Ingot + 3KL CO2`)
- Hafnia-Zirconia decomposes into Hafnia + Zirconia (was a missing link in this chain)
- A recipe conflict w/ Hafnia & Zirconia tetrachloride was fixed, so the Hafnia chain is now accessible
- Added a recipe for rare earth dust use (there was none with the new lanthanides chain):

mo-recycle

The only slight issue is with Cerium, Gadolinium, and some other things that have no practical use. Perhaps gaps something for modpack authors to fill in, or something to integrate with Naq/Echo.

### CODE REVIEW

**Comment by NemEzanevem** [comment]
Wow, I didn't really expect anyone to go through and fix some issues I couldn't see... Thank you!

I will release the mod very soon, perhaps today if i don't find any other issues.

I'm also planning to rework the CF/Modrinth/GH Page for GCYR & GT:EC

Possibly even somekind of Tralier for GCYR

I still need to work on the Echo circuit chain, if you have any ideas on how could that work, just hit me up (My main dillemma is i don't really want to rush it, or make it a new Wetware with little changes, + I also plan on some other custom circuit stuff)

**Comment by jmoiron** [comment]
Thanks :)

There are only a few remaining issues I couldn't figure out.

One is that the old osmium single-block distillery recipes make osmium unattainable without a DT, because the single-block recipes are made and named automatically by the `DISTILLATION_RECIPES` builder.  This could be fixed easily with recipe removal, but that's not working for GTCEU recipes for whatever reason. I've been slowly pinging Mikerooni on the discord and he's been looking into it.  I think this can wait til after a CF/Modrinth release.

Another issue is that while the GTEC fluids show up in JEI, none of the dusts do.  It makes it pretty hard to explore the processing chains;  I had to make a ton of bookmarks.  I'm not really sure why, but if this is just a setting somewhere I suggest changing it.  If it's a bug, I'll make some noise about it on gtceu discord.

Finally, i'm having a hard time getting `gradlew runData` to work reliably.  Reprecipitated Platinum is _still_ an issue;  I think the `hu_hu.json` lang file doesn't have the correct resource string.  I didn't really know how the resources worked when I tried to contribute the fix last time, but I think I'm figuring it out.

That said, a release would be much appreciated!  I'd love to get my WIP modpack out there.

I'll have a think about the echo circuits.  In my opinion, post-game content is the easiest to wait on, few players ever even make it to UHV in the first place and there's not a ton of content there right now.

I'm also interested in the naqadah line, because I want to add naq reactors to my pack.

**Comment by NemEzanevem** [comment]
Okay, I will start looking into some final fixes before pushing a release which im gonna release as the first alpha hopefully

Also, dont mind the uhhh Hungarian Translation thats a side project im doing, i can probably just remove it for now

**Comment by jmoiron** [comment]
Was wondering why that file overlap with a real language code 😆

**Comment by NemEzanevem** [comment]
Okay, the next Github Release should be up to date with your changes, & Probably going to be the version that im releasing!

There are also the Rare Earth(I, II, II) Ores which i may also add for some extra complexity, possibly integrate it with our other mod Gregicality Rocketry, but make it optional

Btw, I'm thinking about adding NaqLine it's just the Neutron Activator multiblock is a bit uhh complicated and i may want to end up changing some stuff on it..

**Comment by NemEzanevem** [comment]
Apparently JEI now shows everything from the Mod since i updated GTCEu to 1.1.3.b in the dependency

image

**Comment by NemEzanevem** [comment]
The Release Version Numbering is a bit up so I'll link it here:

https://github.com/Argent-Matter/Gregtech-Extended-Chemistry/releases/tag/0.1.0.alpha

**Pull request merged**
